### ISSUE TITLE
Unable to load material

### ISSUE THREAD

**Issue by KreBicycle** [KeyuWu-CS/MonoHair#3]
Found error while running prepare_data.py

> `unable to load materials from: ./bust_long_c.obj.mtl
unable to load materials from: ./bust_long_c.obj.mtl
unable to load materials from: material.mtl
unable to load materials from: ./bust_long_c.obj.mtl
Traceback (most recent call last):
File "/opt/data/private/chy/workspace/MonoHair/prepare_data.py", line 169, in <module>
render_bust_hair_depth(os.path.join(root,'ours/colmap_points.obj'), camera_path, save_root,bust_path=bust_path,Headless=Headless)
File "/opt/data/private/chy/workspace/MonoHair/Utils/Render_utils.py", line 321, in render_bust_hair_depth
Render = Renderer(camera, Width=image_size[1], Height=image_size[0], Headless=Headless)
File "/opt/data/private/chy/workspace/MonoHair/Utils/Render_utils.py", line 217, in init
self.ctx = moderngl.create_context(standalone=True, backend='egl', libgl='libGL.so.1',
File "/root/miniconda3/envs/MonoHair/lib/python3.10/site-packages/moderngl/init.py", line 1936, in create_context
ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
File "/root/miniconda3/envs/MonoHair/lib/python3.10/site-packages/glcontext/init.py", line 120, in create
return egl.create_context(**kwargs)
Exception: requested device index 0, but found 0 devices`
I thought it may be short of GPU, but I found nothing wrong. So I think maybe the error came from bust_long_c.obj.mtl, and I didn't find this file. There is only a similar bust_long.obj in directory Bust. I followed readme to install the repository, but I only downloaded processed_data. Did I miss anyting?

**Comment by s58vshar** [comment]
I ran into same issue but I copied the files from provided data in One Drive folder.

**Comment by KreBicycle** [comment]
> I ran into same issue but I copied the files from provided data in One Drive folder.

You mean I should download the "full" folder?

**Comment by KeyuWu-CS** [comment]
We don't use .tml file. And this issue maybe because the headless rendering.  If you use windows with a display, you shouldn't have this problem. If you use Linux, you should refer to the [headless rendering with moderngl](https://moderngl.readthedocs.io/en/5.6.2/the_guide/headless_ubunut18_server.html). @KreBicycle

**Comment by KeyuWu-CS** [comment]
In prepare_data.py. We [render depth ](https://github.com/KeyuWu-CS/MonoHair/blob/81f91d7438663919a104f7ef72c4dedbce565445/prepare_data.py#L169)using moderngl. It's a kind of headless rendering. If you download our [full data](https://onedrive.live.com/?authkey=%21AGgGaslXnM2IPCk&id=189E63F34198D017%21108&cid=189E63F34198D017), you can skip data prepare stage, just using our rendered depth maps.

**Comment by KeyuWu-CS** [comment]
@KreBicycle You also can try to use Windows with display to render depth, and execute the rest steps with Linux

**Comment by 0mil** [comment]
> We don't use .tml file. And this issue maybe because the headless rendering. If you use windows with a display, you shouldn't have this problem. If you use Linux, you should refer to the [headless rendering with moderngl](https://moderngl.readthedocs.io/en/5.6.2/the_guide/headless_ubunut18_server.html). @KreBicycle 

@KreBicycle 
This way works well for me. I also ran this project  on Linux(specifically docker with cuda:11.3.1-cudnn8-devel-ubuntu20.04 image).

**Comment by Reus59** [comment]
> > We don't use .tml file. And this issue maybe because the headless rendering. If you use windows with a display, you shouldn't have this problem. If you use Linux, you should refer to the [headless rendering with moderngl](https://moderngl.readthedocs.io/en/5.6.2/the_guide/headless_ubunut18_server.html). @KreBicycle
> 
> But I didn't launch any headless rendering, just executed the script of prepare_data which is on your provided data. I don't think there is anything to do with headless rendering in my view. Is there anything wrong?

I also meet the same problem, how did you solve it?
