### ISSUE TITLE
python prepare_data.py --yaml=configs/reconstruct/big_wavy1 crash

### ISSUE THREAD

**Issue by LaurentGarcia** [KeyuWu-CS/MonoHair#5]
Hello I am trying to execute the first step with:

1. cp data_processed/big_wavy1 to data/big_wavy1
2. python prepare_data.py --yaml=configs/reconstruct/big_wavy1
3. setting configurations...
loading configs/reconstruct/base.yaml...
loading configs/reconstruct/big_wavy1.yaml...
* HairGenerate:
   * connect_dot_threshold: 0.8
   * connect_scalp: True
   * connect_segments: True
   * connect_threshold: 0.0025
   * connect_to_guide: None
   * dist_to_root: 6
   * generate_segments: True
   * grow_threshold: 0.85
   * out_ratio: 0.35
* PMVO:
   * conf_threshold: 0.15
   * filter_point: True
   * genrate_ori_only: None
   * infer_inner: True
   * num_sample_per_grid: 4
   * optimize: True
   * patch_size: 7
   * threshold: 0.025
   * visible_threshold: 1
* bbox_min: [-0.32, -0.32, -0.24]
* bust_to_origin: [0.006, -1.644, 0.01]
* camera_path: camera/calib_data/wky07-22/cam_params.json
* check_strands: True
* cpu: None
* data:
   * Conf_path: conf
   * Occ3D_path: ours/Occ3D.mat
   * Ori2D_path: best_ori
   * Ori3D_path: ours/Ori3D.mat
   * bust_path: ours/bust_long_tsfm.obj
   * case: big_wavy1
   * depth_path: render_depth
   * frame_interval: 7
   * image_size: [1920, 1080]
   * mask_path: hair_mask
   * raw_points_path: ours/colmap_points.obj
   * root: data
   * scalp_path: ours/scalp_tsfm.obj
   * strands_path: ours/world_str_raw.dat
* device: cuda:0
* gpu: 0
* image_camera_path: ours/cam_params.json
* infer_inner:
   * render_data: True
   * run_mvs: True
* name: 10-16
* ngp:
   * marching_cubes_density_thresh: 3.0
* output_root: output
* prepare_data:
   * fit_bust: None
   * process_bust: True
   * process_camera: True
   * process_imgs: True
   * render_depth: True
   * run_ngp: True
   * select_images: True
* save_path: refine
* scalp_diffusion: None
* seed: 0
* segment:
   * CDGNET_ckpt: assets/CDGNet/LIP_epoch_149.pth
   * MODNET_ckpt: assets/MODNet/modnet_photographic_portrait_matting.ckpt
   * scene_path: None
* vsize: 0.005
* yaml: configs/reconstruct/big_wavy1
(creating new options file...)
distance: 2.254131284488828
distance: 2.2541312844888277
16:49:16 SUCCESS  Initialized CUDA 12.5. Active GPU is #0: NVIDIA GeForce RTX 4090 [89]
16:49:16 INFO     Loading NeRF dataset from
16:49:16 WARNING    data\big_wavy1\colmap\base_cam.json does not contain any frames. Skipping.
16:49:16 WARNING    data\big_wavy1\colmap\base_transform.json does not contain any frames. Skipping.
16:49:16 WARNING    data\big_wavy1\colmap\cam_params.json does not contain any frames. Skipping.
16:49:16 WARNING    data\big_wavy1\colmap\key_frame.json does not contain any frames. Skipping.
16:49:16 INFO       data\big_wavy1\colmap\transforms.json
16:49:20 SUCCESS  Loaded 1189 images after 3s
16:49:20 INFO       cam_aabb=[min=[-1.17578,-0.902506,-0.0814099], max=[1.78049,1.91326,1.84811]]
16:49:22 INFO     Loading network snapshot from: data\big_wavy1\colmap\base.ingp
16:49:22 INFO     GridEncoding:  Nmin=16 b=2.43803 F=4 T=2^19 L=8
16:49:22 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
16:49:22 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
16:49:22 INFO       total_encoding_params=12855296 total_network_params=10240
Screenshot transforms from  data\big_wavy1\colmap/base_transform.json
Generating mesh via marching cubes and saving to data\big_wavy1\colmap/base.obj. Resolution=[512,512,512], Density Threshold=3.0
16:49:22 INFO     #vertices=3666953 #triangles=7305214
range(0, 16)
rendering data\big_wavy1\trainning_images/capture_images\000.png
rendering data\big_wavy1\trainning_images/capture_images\001.png
rendering data\big_wavy1\trainning_images/capture_images\002.png
rendering data\big_wavy1\trainning_images/capture_images\003.png
rendering data\big_wavy1\trainning_images/capture_images\004.png
rendering data\big_wavy1\trainning_images/capture_images\005.png
rendering data\big_wavy1\trainning_images/capture_images\006.png
rendering data\big_wavy1\trainning_images/capture_images\007.png
rendering data\big_wavy1\trainning_images/capture_images\008.png
rendering data\big_wavy1\trainning_images/capture_images\009.png
rendering data\big_wavy1\trainning_images/capture_images\010.png
rendering data\big_wavy1\trainning_images/capture_images\011.png
rendering data\big_wavy1\trainning_images/capture_images\012.png
rendering data\big_wavy1\trainning_images/capture_images\013.png
rendering data\big_wavy1\trainning_images/capture_images\014.png
rendering data\big_wavy1\trainning_images/capture_images\015.png
unable to load materials from: ./bust_long_c.obj.mtl
unable to load materials from: ./bust_long_c.obj.mtl
unable to load materials from: material.mtl
unable to load materials from: ./bust_long_c.obj.mtl
Start calculating masks!
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 169/169 [00:10<00:00, 16.46it/s]
Start calculating hair masks!
Traceback (most recent call last):
  File "C:\Users\Lauren\Documents\Source\MonoHair\prepare_data.py", line 182, in <module>
    calculate_mask(segment_args)
  File "C:\Users\Lauren\Documents\Source\MonoHair\preprocess_capture_data\calc_masks.py", line 171, in calculate_mask
    for key, nkey in zip(state_dict_old.keys(), state_dict.keys()):
RuntimeError: OrderedDict mutated during iteration

**Comment by 0mil** [comment]
@KeyuWu-CS 
I also have been experiencing above issue. I am trying to resolve it, but it is not easy.
Could I get some advice on this? 
Thank you in advance for your help.

**Comment by 0mil** [comment]
@KeyuWu-CS 
I am also experiencing the above issue. I am trying to find a solution, but it is not easy. Could I get some advice on this?
Thank you in advance for your help.

**Comment by KeyuWu-CS** [comment]
It's wired, I don't face this problem in different machines. I guess you download different CDGNet pretrained model (Their repo have two model with same name). I uploaded the model I used on [one drive,](https://onedrive.live.com/?id=189E63F34198D017%21131&cid=189E63F34198D017) you can try again. You also can refer to the [mask calculate of NeuralHairCut](https://github.com/SamsungLabs/NeuralHaircut/blob/main/preprocess_custom_data/calc_masks.py). We used the same method.

**Comment by 0mil** [comment]
@KeyuWu-CS 
Thank you for your quick response! I'll try to resolve the issue using the method you suggested. If successful, I'll support with other similar issues.  👍👍

**Comment by 0mil** [comment]
@KeyuWu-CS @LaurentGarcia 
I have tested NeuralHairCut and found no issues in the code. I think that the `OrderedDict Runtime Error` occurs only in `Python 3.10` and can be fixed with a simple code changes(Please refer to the PR I submitted for this.). However, a new issue arise. Despite confirming that the provided CDGNet model and checkpoint are the same, the following problem persists. This might be due to library version differences. To resolve this, I have a few questions:

* Please, could you confirm that the current code environment is the same as specified in `readme.md` and `requirements.txt`?

* If `prepare_data.py` and other operations were executed in different environments, could you provide the `environment` and `requirements.txt` used to run `prepare_data.py`?

Providing this information will help us resolve the issue. Thank you!

```bash
Traceback (most recent call last):
  File "/workspace/prepare_data.py", line 182, in <module>
    calculate_mask(segment_args)
  File "/workspace/preprocess_capture_data/calc_masks.py", line 190, in calculate_mask
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResNet:
        Unexpected key(s) in state_dict: "layer5.stages.0.2.weight", "layer5.stages.0.2.bias", "layer5.stages.0.2.running_mean", "layer5.stages.0.2.running_var", "layer5.stages.1.2.weight", "layer5.stages.1.2.bias",
 "layer5.stages.1.2.running_mean", "layer5.stages.1.2.running_var", "layer5.stages.2.2.weight", "layer5.stages.2.2.bias", "layer5.stages.2.2.running_mean", "layer5.stages.2.2.running_var", "layer5.stages.3.2.weight", "layer5.stages.3.2.bias", 
"layer5.stages.3.2.running_mean", "layer5.stages.3.2.running_var", "layer5.bottleneck.1.weight", "layer5.bottleneck.1.bias", "layer5.bottleneck.1.running_mean", "layer5.bottleneck.1.running_var", 
"edge_layer.conv1.1.weight", "edge_layer.conv1.1.bias", "edge_layer.conv1.1.running_mean", "edge_layer.conv1.1.running_var", "edge_layer.conv2.1.weight", "edge_layer.conv2.1.bias", "edge_layer.conv2.1.running_mean", "edge_layer.conv2.1.running_var", 
"edge_layer.conv3.1.weight", "edge_layer.conv3.1.bias", "edge_layer.conv3.1.running_mean", "edge_layer.conv3.1.running_var", "layer6.conv1.1.weight", "layer6.conv1.1.bias", "layer6.conv1.1.running_mean", 
"layer6.conv1.1.running_var", "layer6.conv2.1.weight", "layer6.conv2.1.bias", "layer6.conv2.1.running_mean", "layer6.conv2.1.running_var", "layer6.conv3.1.weight", "layer6.conv3.1.bias", "layer6.conv3.1.running_mean", "layer6.conv3.1.running_var", "layer6.conv3.3.weight", "layer6.conv3.3.bias", "layer6.conv3.3.running_mean", 
"layer6.conv3.3.running_var", "layer7.1.weight", "layer7.1.bias", "layer7.1.running_mean", "layer7.1.running_var". 
        size mismatch for layer6.conv2.0.weight: copying a param with shape torch.Size([48, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([48, 256, 3, 3]).
        size mismatch for layer6.conv3.0.weight: copying a param with shape torch.Size([256, 304, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 304, 3, 3]).
        size mismatch for layer7.0.weight: copying a param with shape torch.Size([256, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1024, 3, 3]).
```

**Comment by KeyuWu-CS** [comment]
I just run it again, I don't face this problem. My environment is python 3.10.12 . And I print all the library here. 

absl-py                      2.1.0
addict                       2.4.0
albumentations               1.3.1
argcomplete                  3.4.0
astroid                      3.2.2
asttokens                    2.4.1
astunparse                   1.6.3
attrs                        23.2.0
autopep8                     2.3.1
backcall                     0.2.0
beautifulsoup4               4.12.3
bleach                       6.1.0
blinker                      1.8.2
certifi                      2024.6.2
charset-normalizer           3.3.2
chumpy                       0.70
click                        8.1.7
cloudpickle                  3.0.0
coloredlogs                  15.0.1
colorlog                     6.8.2
comm                         0.2.2
commentjson                  0.9.0
ConfigArgParse               1.7
contourpy                    1.2.1
cycler                       0.12.1
cyclonedds                   0.10.5
Cython                       3.0.10
dash                         2.17.1
dash-core-components         2.0.0
dash-html-components         2.0.0
dash-table                   5.0.0
decorator                    5.1.1
defusedxml                   0.7.1
dill                         0.3.8
distlib                      0.3.8
dm-tree                      0.1.8
docker-pycreds               0.4.0
docopt                       0.6.2
docutils                     0.21.2
easydict                     1.13
einops                       0.8.0
exceptiongroup               1.2.1
executing                    2.0.1
face-alignment               1.4.1
face-detection-tflite        0.6.0
fastcore                     1.5.46
fastjsonschema               2.19.1
filelock                     3.15.1
flake8                       7.1.0
Flask                        3.0.3
flatbuffers                  24.3.25
fonttools                    4.53.0
fvcore                       0.1.5.post20220512
gast                         0.5.4
ghapi                        1.0.5
gitdb                        4.0.11
GitPython                    3.1.43
glcontext                    2.5.0
google-pasta                 0.2.0
graphviz                     0.20.3
grpcio                       1.64.1
h5py                         3.11.0
humanfriendly                10.0
idna                         3.7
imageio                      2.34.1
importlib_metadata           7.1.0
iniconfig                    2.0.0
insightface                  0.7.3
iopath                       0.1.10
ipdb                         0.13.13
ipython                      8.12.3
ipywidgets                   8.1.3
isort                        5.13.2
itsdangerous                 2.2.0
jedi                         0.19.1
Jinja2                       3.1.4
joblib                       1.4.2
jsonschema                   4.22.0
jsonschema-specifications    2023.12.1
jupyter_client               8.6.2
jupyter_core                 5.7.2
jupyterlab_pygments          0.3.0
jupyterlab_widgets           3.0.11
keras                        3.3.3
kiwisolver                   1.4.5
kornia                       0.7.2
kornia_rs                    0.1.3
lark-parser                  0.7.8
lazy_loader                  0.4
libclang                     18.1.1
lightning-utilities          0.11.2
llvmlite                     0.43.0
loguru                       0.7.2
lpips                        0.1.4
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.0
matplotlib-inline            0.1.7
mccabe                       0.7.0
mdurl                        0.1.2
mistune                      3.0.2
ml-dtypes                    0.3.2
moderngl                     5.10.0
mpmath                       1.3.0
namex                        0.0.8
nbclient                     0.10.0
nbconvert                    7.16.4
nbformat                     5.10.4
nest-asyncio                 1.6.0
networkx                     3.3
nox                          2024.4.15
numba                        0.60.0
numpy                        1.23.5
nvidia-cublas-cu11           11.10.3.66
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cudnn-cu11            8.5.0.96
onnx                         1.16.1
onnxruntime                  1.18.0
open3d                       0.18.0
opencv-python                4.10.0.82
opencv-python-headless       4.10.0.82
opt-einsum                   3.3.0
optree                       0.11.0
packaging                    24.1
pandas                       2.2.2
pandocfilters                1.5.1
parso                        0.8.4
pexpect                      4.9.0
pickleshare                  0.7.5
pillow                       10.3.0
pip                          24.0
pipreqs                      0.5.0
platformdirs                 4.2.2
plotly                       5.22.0
pluggy                       1.5.0
portalocker                  2.8.2
prettytable                  3.10.0
prompt_toolkit               3.0.47
protobuf                     4.25.3
psutil                       5.9.8
ptyprocess                   0.7.0
pure-eval                    0.2.2
pycodestyle                  2.12.0
pyflakes                     3.2.0
Pygments                     2.18.0
pylint                       3.2.3
pyntcloud                    0.3.1
pyparsing                    3.1.2
pyquaternion                 0.9.9
pytest                       8.2.2
python-dateutil              2.9.0.post0
pytorch3d                    0.7.2
pytz                         2024.1
PyYAML                       6.0.1
pyzmq                        26.0.3
qudida                       0.0.4
referencing                  0.35.1
requests                     2.32.3
retrying                     1.3.4
rich                         13.7.1
rich-click                   1.8.3
rpds-py                      0.18.1
scikit-image                 0.23.2
scikit-learn                 1.5.0
scipy                        1.13.1
sentry-sdk                   2.5.1
setproctitle                 1.3.3
setuptools                   59.6.0
six                          1.16.0
smmap                        5.0.1
soupsieve                    2.5
stack-data                   0.6.3
sympy                        1.12.1
tabulate                     0.9.0
tenacity                     8.3.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorboardX                 2.6.2.2
tensorflow                   2.16.1
tensorflow-io-gcs-filesystem 0.37.0
tensorflow-probability       0.24.0
termcolor                    2.4.0
threadpoolctl                3.5.0
tifffile                     2024.5.22
tinycss2                     1.3.0
tinycudann                   1.7
tomli                        2.0.1
tomlkit                      0.12.4
torch                        1.11.0+cu113
torchaudio                   0.11.0+cu113
torchmetrics                 1.4.0.post0
torchvision                  0.12.0+cu113
torchviz                     0.0.2
tornado                      6.4.1
tqdm                         4.66.4
traitlets                    5.14.3
trimesh                      3.12.6
typing_extensions            4.10.0
tzdata                       2024.1
urllib3                      2.2.1
virtualenv                   20.26.2
wandb                        0.17.1
wcwidth                      0.2.13
webencodings                 0.5.1
Werkzeug                     3.0.3
wheel                        0.43.0
widgetsnbextension           4.0.11
wrapt                        1.16.0
yacs                         0.1.8
yarg                         0.1.9
zipp                         3.19.2

**Comment by LaurentGarcia** [comment]
This is my one: 

# Name                    Version                   Build  Channel
absl-py                   2.1.0                    pypi_0    pypi
albumentations            1.3.1                    pypi_0    pypi
argcomplete               3.4.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.2             haa95532_0
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
cmake                     3.30.1                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
colorlog                  6.8.2                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
commentjson               0.9.0                    pypi_0    pypi
configargparse            1.7                      pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cyclonedds                0.10.5                   pypi_0    pypi
cython                    3.0.10                   pypi_0    pypi
dash                      2.17.1                   pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
distlib                   0.3.8                    pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
easydict                  1.13                     pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
face-alignment            1.4.1                    pypi_0    pypi
face-detection-tflite     0.6.0                    pypi_0    pypi
fastcore                  1.5.54                   pypi_0    pypi
fastjsonschema            2.20.0                   pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fvcore                    0.1.5.post20220512          pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
ghapi                     1.0.5                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
glcontext                 2.5.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.65.1                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
importlib-metadata        8.1.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
insightface               0.7.3                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
ipdb                      0.13.13                  pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipywidgets                8.1.3                    pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyterlab-widgets        3.0.11                   pypi_0    pypi
keras                     3.4.1                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.2                    pypi_0    pypi
kornia-rs                 0.1.5                    pypi_0    pypi
lark-parser               0.7.8                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libclang                  18.1.1                   pypi_0    pypi
libffi                    3.4.4                hd77b12b_1
lightning-utilities       0.11.6                   pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
ml-dtypes                 0.3.2                    pypi_0    pypi
moderngl                  5.10.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
nox                       2024.4.15                pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
onnx                      1.16.1                   pypi_0    pypi
onnxruntime               1.18.0                   pypi_0    pypi
open3d                    0.18.0                   pypi_0    pypi
opencv-python             4.10.0.82                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.14               h827c3e9_0
opt-einsum                3.3.0                    pypi_0    pypi
optree                    0.12.1                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0
platformdirs              4.2.2                    pypi_0    pypi
plotly                    5.23.0                   pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
portalocker               2.10.1                   pypi_0    pypi
prettytable               3.10.2                   pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
protobuf                  4.25.3                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyntcloud                 0.3.1                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
pytest                    8.2.2                    pypi_0    pypi
python                    3.10.12              he1021f5_0
python-dateutil           2.9.0.post0              pypi_0    pypi
python-graphviz           0.20.3                   pypi_0    pypi
pytorch3d                 0.7.7                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
retrying                  1.3.4                    pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rich-click                1.8.3                    pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
scikit-image              0.23.2                   pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
sentry-sdk                2.10.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                59.6.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.12.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.5.0                    pypi_0    pypi
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tensorflow                2.16.1                   pypi_0    pypi
tensorflow-intel          2.16.1                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
tensorflow-probability    0.24.0                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.7.21                pypi_0    pypi
tinycudann                1.7                      pypi_0    pypi
tk                        8.6.14               h0416ee5_0
tomli                     2.0.1                    pypi_0    pypi
torch                     1.11.0+cu113             pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchmetrics              1.4.0.post0              pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
torchviz                  0.0.2                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
trimesh                   3.12.6                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.2                 h2eaa2aa_4
virtualenv                20.26.3                  pypi_0    pypi
vs2015_runtime            14.29.30133          h43f2093_4
wandb                     0.17.1                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.3                    pypi_0    pypi
wheel                     0.43.0          py310haa95532_0
widgetsnbextension        4.0.11                   pypi_0    pypi
win32-setctime            1.1.0                    pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h8cc25b3_1
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1

**Comment by LaurentGarcia** [comment]
Hello @KeyuWu-CS  I can confirm than it's working! Download your CDGNet made the magic.

**Comment by 0mil** [comment]
> @0mil @LaurentGarcia It's wired, I don't face this problem in different machines. I guess you download different CDGNet pretrained model (Their repo have two model with same name). I uploaded the model I used on [one drive,](https://onedrive.live.com/?id=189E63F34198D017%21131&cid=189E63F34198D017) you can try again. You also can refer to the [mask calculate of NeuralHairCut](https://github.com/SamsungLabs/NeuralHaircut/blob/main/preprocess_custom_data/calc_masks.py). We used the same method.

@KeyuWu-CS
You are right. It works perfectly. This is really impressive research!! I look forward to your future works! Thank you for sharing!!
