### ISSUE TITLE
python infer_inner.py --yaml=configs/reconstruct/big_wavy1 - ImportError: cannot import name 'egl' from 'glcontext'

### ISSUE THREAD

**Issue by LaurentGarcia** [KeyuWu-CS/MonoHair#7]
Another Step error :)

generate segments...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281827/281827 [10:57<00:00, 428.35it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281827/281827 [04:13<00:00, 1112.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281827/281827 [03:32<00:00, 1325.13it/s]
done...
Traceback (most recent call last):
  File "C:\Users\Lauren\Documents\Source\MonoHair\infer_inner.py", line 71, in <module>
    render_data(camera ,strands ,vertices ,faces ,[1280 ,720] ,os.path.join(args.data.root ,'imgs'))
  File "C:\Users\Lauren\Documents\Source\MonoHair\Utils\Render_utils.py", line 270, in render_data
    Render = Renderer(camera, Width=image_size[1], Height=image_size[0], Headless=True)
  File "C:\Users\Lauren\Documents\Source\MonoHair\Utils\Render_utils.py", line 217, in __init__
    self.ctx = moderngl.create_context(standalone=True, backend='egl', libgl='libGL.so.1',
  File "C:\Users\Lauren\miniconda3\envs\MonoHair\lib\site-packages\moderngl\__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "C:\Users\Lauren\miniconda3\envs\MonoHair\lib\site-packages\glcontext\__init__.py", line 49, in get_backend_by_name
    return _egl()
  File "C:\Users\Lauren\miniconda3\envs\MonoHair\lib\site-packages\glcontext\__init__.py", line 106, in _egl
    from glcontext import egl
ImportError: cannot import name 'egl' from 'glcontext' (C:\Users\Lauren\miniconda3\envs\MonoHair\lib\site-packages\glcontext\__init__.py)

**Comment by LaurentGarcia** [comment]
Quick fix for Windows:

 if Headless:
            # self.ctx = moderngl.create_context(standalone=True, libgl='libGL.so.1', libx11='libX11.so.6')
            #self.ctx = moderngl.create_context(standalone=True, backend='egl', libgl='libGL.so.1',
            #                                   libegl='libEGL.so.1', )
            self.ctx = moderngl.create_context(standalone=True)

Maybe it's a good idea to have some windows specific headers. :)

**Comment by 0mil** [comment]
@LaurentGarcia 

Thanks for sharing information about Windows.

I tried to run this project in Windows OS.
However, I encountered various dependencies problem while installing Pytorch3D and tiny-cuda-nn.

Could you provide the specific environments details used on your Windows OS, such as CUDA version, Pytorch3D version, Torch version, and tiny-cuda-nn version?
